[package]
name = "merak-front-ts"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
merak-ir.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_parser.workspace = true
oxc_span.workspace = true
oxc_syntax.workspace = true
serde_json.workspace = true
